# Deployment e Service para o Processo 1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: app-1-container
        image: token-ring-app:latest # Nome da imagem que vamos construir
        imagePullPolicy: IfNotPresent # Garante que o minikube use a imagem local
        ports:
        - containerPort: 8000
        env:
        - name: PROCESS_ID
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: app-1 # Este nome será o hostname para outros pods se comunicarem
spec:
  type: NodePort
  selector:
    app: app-1
  ports:
  - protocol: TCP
    port: 8000       # Porta interna do serviço
    targetPort: 8000 # Porta do contêiner
    nodePort: 30001  # Porta externa para acesso via 'minikube ip'
---
# Deployment e Service para o Processo 2 (similar ao 1)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-2
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
      - name: app-2-container
        image: token-ring-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: PROCESS_ID
          value: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: app-2
spec:
  type: NodePort
  selector:
    app: app-2
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30002
---
# Deployment e Service para o Processo 3 (similar ao 1)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-3
  template:
    metadata:
      labels:
        app: app-3
    spec:
      containers:
      - name: app-3-container
        image: token-ring-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: PROCESS_ID
          value: "3"
---
apiVersion: v1
kind: Service
metadata:
  name: app-3
spec:
  type: NodePort
  selector:
    app: app-3
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30003