# Deployment e Service para o Processo 1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bully-app-1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bully-app-1
  template:
    metadata:
      labels:
        app: bully-app-1
    spec:
      containers:
      - name: bully-app-1-container
        image: bully-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: PROCESS_ID
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: app-1 # Hostname para outros pods
spec:
  type: NodePort
  selector:
    app: bully-app-1
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30011
---
# Deployment e Service para o Processo 2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bully-app-2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bully-app-2
  template:
    metadata:
      labels:
        app: bully-app-2
    spec:
      containers:
      - name: bully-app-2-container
        image: bully-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: PROCESS_ID
          value: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: app-2
spec:
  type: NodePort
  selector:
    app: bully-app-2
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30012
---
# Deployment e Service para o Processo 3
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bully-app-3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bully-app-3
  template:
    metadata:
      labels:
        app: bully-app-3
    spec:
      containers:
      - name: bully-app-3-container
        image: bully-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: PROCESS_ID
          value: "3"
---
apiVersion: v1
kind: Service
metadata:
  name: app-3
spec:
  type: NodePort
  selector:
    app: bully-app-3
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30013